name: image_cacheing
description: image_cacheing will cache image that given to url params. Thus increasing the speed of image loading at next time you load the image. This is support on android devices as of now.
version: 0.0.2
homepage: https://github.com/evolvingkid/image_cacheing

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
 

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.0
  crypto: ^3.0.1
  path_provider: ^2.0.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
